version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: cdarrell
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: cdarrell@student.42.fr
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    ports:
      - "8081:80"
