version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: cdarrell
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"

